### ISSUE TITLE
Runtime 2.2.0 is not working

### ISSUE THREAD

**Issue by oscartbeaumont** [vercel/edge-runtime#319]
## Bug Report

The following code taken from the example docs works on version `2.1.4` but not on version `2.2.0`.

```ts
import { EdgeRuntime } from "edge-runtime";

const initialCode = `
addEventListener('fetch', event => {
  const { searchParams } = new URL(event.request.url)
  const url = searchParams.get('url')
  return event.respondWith(fetch(url))
})`;

const edgeRuntime = new EdgeRuntime({ initialCode });

const response = await edgeRuntime.dispatchFetch("https://example.com");

// If your code logic performs asynchronous tasks, you should await them.
// https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil
await response.waitUntil();
```

When running on version `2.2.0` I get the error:

```
TSError: ⨯ Unable to compile TypeScript:
cli2.ts:10:39 - error TS2345: Argument of type '{ initialCode: string; }' is not assignable to parameter of type 'EdgeVMOptions<EdgeContext>'.
  Object literal may only specify known properties, and 'initialCode' does not exist in type 'EdgeVMOptions<EdgeContext>'.

10 const edgeRuntime = new EdgeRuntime({ initialCode });
                                         ~~~~~~~~~~~
cli2.ts:12:36 - error TS2339: Property 'dispatchFetch' does not exist on type 'EdgeVM<EdgeContext>'.

12 const response = await edgeRuntime.dispatchFetch("https://example.com");
                                      ~~~~~~~~~~~~~

    at createTSError (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/oscar/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.0.6_typescript@4.7.4/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:173:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:616:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:472:11) {
  diagnosticCodes: [ 2345, 2339 ]
}
```

If I disable typechecking I get the following error proving that the Typescript error is valid:

```
TypeError: edgeRuntime.dispatchFetch is not a function
    at file:///Users/oscar/Desktop/saas-starter2/cli2.ts:14:36
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
```

I would expect this code to still work but if the arguments have changed it would be good if the documentation could be updated.

**Comment by oscartbeaumont** [comment]
When using version `2.1.4` I actually get the error:
```
TypeError: Failed to parse URL from null
```
but this error is coming from the `initialCode` block and not the edge-runtime itself. Replacing the block with a "Hello World" response fixes the error.

**Comment by Kikobeats** [comment]
Hello, @oscartbeaumont!

I updated the doc example since it was confusing: https://edge-runtime.vercel.app/getting-started

Also, you don't need to run that code if you just use the edge runtime CLI, or `vercel dev`, or `next dev`; they are wrapping this code for you 🙂

**Comment by oscartbeaumont** [comment]
I have resorted to using the Edge Runtime code directly because as far as I am aware a custom framework can't tell `vercel dev` about the edge functions it creates. I really really want to move back to Vercel CLI so if you've got any pointers or know where I should open an issue, any help would be appreciated!

For some more context, I am building a mini-framework based around SolidJS's `renderToStream`. I made a little CLI that can compile the user's code into an edge function and I am currently outputting it in the Vercel Build Output API v3 format. This works perfectly when deployed to Vercel but I am unable to get a development setup working with it.

The primary challenge is that the edge function needs to be created by my code because I use a custom Vite plugin to inject an SSR manifest  (So my code can know the names of the client bundles Eg. `index-687ghg2.js`).

Using `vercel dev` just runs Vite's dev server which serves the assets but doesn't expose the edge functions as Vercel's CLI has no way of knowing about the edge functions except for maybe checking the `.vercel/output/functions` directory which it unsurprisingly doesn't seem to do.

I also tried creating a custom runtime (following [this](https://github.com/vercel/vercel/blob/main/DEVELOPING_A_RUNTIME.md)) but `vercel dev` throws the following error when using it because I am returning an `EdgeFunction` instead of a `Lambda`.
```
Error: The result of "builder.build()" must be a `Lambda`
```
Interestingly `vercel build` work works fine with this setup so this seems to be a limitation in the dev server only. Do you know much able the Vercel CLI and if this would be a bug or is the intended design? Fixing this would likely be the best solution to my problem!

To workaround this I am using the `edge-runtime` package directly so that I can have it hot reload whenever the Vite devserver emits a change event but it's not a very good solution as it requires bundling the [`edge-handler-template.js`](https://github.com/vercel/vercel/blob/678e13af53d180f804ffe558343af7eacc769ca5/packages/node/src/edge-functions/edge-handler-template.js) and as you have implied it's not designed to be a high-level API. I am also concerned that this setup could cause drift between my dev setup and Vercel's prod environment over time as I also miss out on Vercel's request routing, headers, rewrite, etc that the CLI is able to handle.

I have created a [super minimal reproduction](https://github.com/oscartbeaumont/vercel-cli-custom-ssr) of my setup as code can help to illustrate what I'm saying. If you had any ideas to help they would be greatly appreciated and I love the work you are all doing on the Edge runtime!

**Comment by TooTallNate** [comment]
You are correct that `vercel dev` does not work with the Build Output API. Instead, it is expected that the frontend framework being used (so your mini-framework in your case) offers its own local dev server command (i.e. `next dev` for Next.js), and `vercel dev` simply proxies to that local server as specified the the **Dev Command** in the Project Settings.

So in your case you would want to write a local dev server that utilizes this `edge-runtime` package to provide the proper execution environment, and configure the Dev Command to invoke that server when `vc dev` is run.

We do have plans for something like a `vercel start` command. That _would_ operate on the Build Output API contents, and would be targeted towards framework authors to verify that their Build Output API implementation works correctly before deploying to Vercel. But it wouldn't do "dev" stuff like file watching and re-processing build outputs at runtime, so would not be meant for an end-user to use during development.

**Comment by oscartbeaumont** [comment]
Thanks, both of you for helping!

To me, this feels like such a loss because from what I can see you have most of the runtime APIs in place to support this given a builder can just return a `Lambda` and it works in dev mode with the Vercel CLI acting as a file watcher. From a framework author's perspective, it means they have to not just need to implement the edge runtime into their CLI but they also need to implement their own routing system to set HTTP headers, redirect, and rewrites instead of just being able to use them from the `vercel.json`. I understand a lot of frameworks probably want to do this themselves and that's fair but for something which is relatively simple like I am doing, it means going from a ~100 line Vercel runtime to having a whole CLI that is probably going to end up at least triple that size.

**Comment by oscartbeaumont** [comment]
@Kikobeats I am looking at the updated examples and they still show the usage of both `initialCode` in `new EdgeRuntime({ initialCode })`  and also `.dispatchFetch` which are both shown as invalid by Typescript in version `2.2.0` of the `edge-runtime`. Do you know what I should be using instead?

**Comment by pi0** [comment]
Just came cross this issue since nitro tests for vercel-edge were broken. Sharing if this might help: https://github.com/unjs/nitro/blob/main/test/presets/vercel-edge.test.ts
